### ISSUE TITLE
this.width

### ISSUE THREAD

**Issue by graphis** [iamjpg/Ez-Background-Resize#4]
this.width does not work on the webkit based browsers,
and if it would you will have issues with images wich are not  100% loaded

**Comment by iamjpg** [comment]
Actually, it does work in webkit browsers since "this" is directly referring to the image object passed by the user.

In the code, you'll now see that I'm pre-loading the image with a callback (thus the "this" reference) to get the objects height and width so the user of the plugin doesn't need to pass that info anymore.

These commits aren't on the master branch; they're on the develop branch until I've gotten the chance to test it on IE.  Right now it's working in Safari, Chrome, and Firefox.

**Comment by graphis** [comment]
Hi,

maybe I am wrong, but it does not work on my mac 
os 10.6.x safari: 5.0.1 

for a year I developem my own fullscrenn js thing and I tested a log of these solutions, I always hadd issues with this.width or heigth, wich is a jquery function as far as I remember.

try resizing the window on safari 5 (this is what I got currently at hand) it does not work

---

Sándor Zsolt
designer
70 257 5720
ezsolt@gmail.com
www.graphis.eu

**Comment by iamjpg** [comment]
So, "this" isn't a jQuery function.  It's a pointer to the object being evaluated.  In my plugin "this" is referencing the image object during the .load() callback.  width and height are attributes available on the object (this.width, this.height).

Evaluating an object this way is standard across browsers.

RIght now, the only browser this plugin isn't working on is IE6 (and it never will).  The tested browsers are:

IE7, IE8, Safari 5 (Mac and Windows), Chrome 10, FireFox 3 and 4.

I recently made a change which might fix the issue you're seeing with the plugin.  I created a new GitHub page for testing the latest releases here:

http://iamjpg.github.com/jQuery-Ez-Background-Resize/

Hopefully you were looking at a bad build and this latest build fixes the issues you're seeing.

If you're still seeing problems, send me a screenshot of the page along with the error in the console?  I would really appreciate it.

Cheers,
J.P.
